package com.nigma.module_twilio.utils

const val ACTION_VOIP_CONNECT_ROOM = "action:VOIP-ROOM-CONNECT"
const val ACTION_VOIP_DISCONNECT_ROOM = "action:VOIP-ROOM-DISCONNECT"

const val ACTION_VOIP_HANDLE_MIC = "action:ACTION_VOIP_HANDLE_MIC"
const val ACTION_VOIP_HANDLE_AUDIO_OUTPUT = "action:ACTION_VOIP_HANDLE_AUDIO_OUTPUT"
const val ACTION_VOIP_HANDLE_CHANGE_AUDIO_DEVICE = "ACTION_CALL_MEDIA_CHANGE_AUDIO_DEVICE"
const val ACTION_VOIP_HANDLE_CAMERA = "action:ACTION_VOIP_HANDLE_CAMERA"
const val ACTION_VOIP_HANDLE_CAMERA_FLIP = "action:ACTION_VOIP_MEDIA_HANDLE_CAMERA_FLIP"

const val KEY_ROOM_NAME = "key:_ROOM_NAME"
const val KEY_ACCESS_TOKEN = "key:_ACCESS_TOKEN"
const val KEY_IS_VOIP_VIDEO_TYPE = "key:_VOIP_TYPE"
const val KEY_USER_OBJECT = "key:_USER_OBJECT"

